# Base Environment
FROM node:16.0.0-alpine
# Set the working directory
WORKDIR /app
# Copy package files
COPY package*.json ./
# Install dependencies
RUN npm install
# Copy all other source code files
COPY . .
# ENV variables
ENV NODE_ENV production
ENV DB_NAME music_space_prod
ENV DB_HOST music-space-my-sg-do-user-14390998-0.b.db.ondigitalocean.com
ENV DB_PORT 25060
ENV DB_USER doadmin
ENV DB_PASSWORD AVNS_bnsctmn7Ga0Aod3SrC7
ENV PORT 8080
ENV SECRET_KEY 123456
ENV MAILGUN_DOMAIN sandboxcb1e782648fe45beb4f0529824fde793.mailgun.org
ENV MAILGUN_API_KEY 76c875309192008ffa12ca58279555e3-135a8d32-1d5ff3ae
ENV STRIPE_PUBLISHABLE_KEY pk_test_51Nh4DCGjGLAwb5UuXW4kfwb50fgJAD6nSgANbIr5113zPWkyIGQgyi4Qd5NUK6pRsOq9Zn63AuH4GtJSnW1j4TYH00dpEhhT84
ENV STRIPE_KEY sk_test_51Nh4DCGjGLAwb5UuSgc5pdTmlBYlx6xyC3SSKV23ct5qyKfeDLShSPVOyaHmZV4dsa8l9JcA2GpKJTZQYvPCBmJR00CH7BqoB6
ENV CLIENT_URL http://localhost:3000
ENV WEBHOOK whsec_b0a4cd6a7813614d5d2c60f89142cfcaab0c8e0123ac3de162947d220c5dc311 

# Expose port 
EXPOSE 8080
# Command to start the application
CMD ["npm", "run", "start"]
#CMD ["node", "index.js"]